---
# tasks file for docker-ce-ansible-role
- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_prereqs_ubuntu }}"

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  apt:
    name: "docker-ce={{ docker_version }}~ce-0~ubuntu"
    state: present
    update_cache: yes
