---
- name: Install prerequisite packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_prereqs_rhel }}"

- name: Import Docker CE repository gpg key
  rpm_key:
    key: "{{ docker_gpg_source }}"
    state: present

- name: Add Docker CE repository
  get_url:
    url: "{{ docker_repo_url }}"
    dest: /etc/yum.repos.d/
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Install Docker CE
  yum:
    name: "{{ docker_source }}"
    state: present
    update_cache: yes
